{% set name = "stdio-mgr" %}
{% set version = "1.0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bskinn/stdio-mgr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6568a823e31481a19c2039557aad5de76072e56140e3498329162ef605077780

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - attrs >=17.1
  run:
    - python >={{ python_min }}
    - attrs >=17.1

test:
  requires:
    - pip
    - pytest
    - pytest-timeout
    - python {{ python_min }}
  imports:
    - stdio_mgr
  source_files:
    - conftest.py
    - tests/
  commands:
    - pip check
    - pytest -v -rsxX -p no:warnings --doctest-glob="README.rst"

about:
  home: https://www.github.com/bskinn/stdio-mgr
  summary: Context manager for mocking/wrapping stdin/stdout/stderr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/bskinn/stdio-mgr

extra:
  recipe-maintainers:
    - bskinn
    - anjos
